# Generated by Django 5.0.6 on 2024-08-17 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_setup', '0007_rename_request_staus_friendrequest_request_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
